<?php
/**
 * @file
 * Code for the Lynchburg Calendar feature.
 */

include_once('lc_calendar.features.inc');

/**
 * Implements hook_ctools_plugin_directory().
 */
function lc_calendar_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_date_format_types.
 */
function lc_calendar_date_format_types() {
  return array(
    'lc_calendar_12_hr' => t('12 hr format'), 
    'lc_calendar_day_month_date_year' => t('Day name, Month name, Date Year'), 
  );
}

/**
 * Implements hook_date_formats.
 */
function lc_calendar_date_formats() {
  $formats = array();

  // Short date formats.
  $formats[] = array(
    'type' => 'lc_calendar_12_hr',
    'format' => 'g:i a',
    'locales' => array(),
  );
  $formats[] = array(
    'type' => 'lc_calendar_day_month_date_year',
    'format' => 'l F j Y',
    'locales' => array(),
  );

  return $formats;
}

/**
 * Implements hook_events
 *
 * @return 
 */
function lc_calendar_menu() {
  $items['events'] = array(
    'page callback' => 'lc_calendar_event_default',
    'access callback' => TRUE,
  );
  return $items;
}
/**
 * Implements hook_form.
 */
function lc_calendar_search_events_form($form, $form_state) {
  // Get the active search terms (if any) from the URL
  $arguments = explode('/', $_GET['q']);
  $active_search_terms = '';
  if (isset($arguments[2])) {
    $active_search_terms = $arguments[2];
  }
  // Handle wildcard.
  if ($active_search_terms == 'all') {
    $active_search_terms = '';
  }

  $search_form = array(
    'search_terms' => array(
      '#type' => 'textfield', 
      '#title' => t(''), 
      '#default_value' => $active_search_terms,
      '#size' => 20, 
      '#maxlength' => 128, 
      '#required' => FALSE,
    ),
    'submit' => array(
      '#type' => 'submit', 
      '#value' => t('Search')
    ),
  );

  return $search_form;
}

/**
 * Submit handler for lc_calendar_search_events_form().
 */
function lc_calendar_search_events_form_submit($form, &$form_state) {
  if (isset($form_state['values']['search_terms'])) {
    $date_range = date('Y-m-d--') . (date('Y') + 3);
    drupal_goto('events/' . $date_range . '/' . $form_state['values']['search_terms']);
  }
}
/**
 * Callback for /events - redirect to current event list.
 */
function lc_calendar_event_default() {
  $category = '';
  if (isset($_GET['category'])) {
    $tid = $_GET['category'];
    if (is_numeric($tid)) {
      $category = $tid;
    }
  }
  $date_range = date('Y-m-d--') . (date('Y-m-d', strtotime("+1 month")));
  if (empty($category)) {
    drupal_goto('events/' . $date_range);
  }
  else {
    drupal_goto('events/' . $date_range, array('query' => array('category' => $category)));
  }
}
