<?php
/**
 * @file
 * Code for the Lynchburg Calendar feature.
 */

include_once('lc_calendar.features.inc');

/*
 * hook_date_format_types
 */
function lc_calendar_date_format_types() {
  return array(
    'lc_calendar_12_hr' => t('12 hr format'), 
    'lc_calendar_day_month_date_year' => t('Day name, Month name, Date Year'), 
  );
}

/*
 * hook_date_formats
 */
function lc_calendar_date_formats() {
  $formats = array();

  // Short date formats.
  $formats[] = array(
    'type' => 'lc_calendar_12_hr',
    'format' => 'g:i a',
    'locales' => array(),
  );
  $formats[] = array(
    'type' => 'lc_calendar_day_month_date_year',
    'format' => 'l F j Y',
    'locales' => array(),
  );

  return $formats;
}

